#!/usr/bin/env python3
"""Turn the arm results into RESULTS.md, applying the decision rules from HYPOTHESES.md.

The rules were fixed before the runs. This script only evaluates them; it does not choose
which comparison to make after seeing the numbers.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PROXY = os.path.dirname(HERE)
RESULTS = os.path.join(PROXY, "results")

FULL_ARMS = ["A_proposed", "B_web_heavy", "C_no_floor", "D_verified_only"]
SEED2 = "A_proposed_seed2"
E_ARMS = ["E1_hard_frozen", "E2_hard_trainable", "E3_warm_trainable"]
LANES = ["general_web", "code", "stem", "reasoning", "agentic", "long_context",
         "indic_A_verified", "indic_B_unverified", "indic_C_translated", "indic_D_synthetic"]
WEB_TOLERANCE = 0.02      # 2% relative, declared in advance


def load(name):
    p = os.path.join(RESULTS, name + ".json")
    if not os.path.exists(p):
        return None
    with open(p) as f:
        return json.load(f)


def fmt(v, nd=4):
    return "—" if v is None else f"{v:.{nd}f}"


def main():
    runs = {n: load(n) for n in FULL_ARMS + [SEED2] + E_ARMS}
    have = {k: v for k, v in runs.items() if v}
    if not have:
        print("no results yet")
        return 1

    A, B, C, D = (runs.get(n) for n in FULL_ARMS)
    s2 = runs.get(SEED2)

    # ---------------------------------------------------------------- seed-noise band
    sigma = {}
    if A and s2:
        for ln in LANES:
            a, b = A["final_bpb"].get(ln), s2["final_bpb"].get(ln)
            if a is not None and b is not None:
                sigma[ln] = abs(a - b)

    out = []
    w = out.append
    w("# Proxy ablation — results\n")
    w("Generated by `scripts/report.py` from `results/*.json`. Decision rules were fixed in")
    w("[HYPOTHESES.md](HYPOTHESES.md) and committed before the runs.\n")

    # ------------------------------------------------------------------------- setup
    ref = A or next(iter(have.values()))
    cfg = ref["config"]
    env = {}
    ep = os.path.join(RESULTS, "environment.json")
    if os.path.exists(ep):
        env = json.load(open(ep))
    w("## What was run\n")
    w(f"- **{ref['params']['total'] / 1e6:.1f}M parameters** "
      f"({ref['params']['non_embedding'] / 1e6:.1f}M non-embedding; the {cfg['vocab_size']:,}-entry "
      f"sarvam1 vocabulary is most of the rest), d_model {cfg['d_model']}, "
      f"{cfg['n_layers']} layers, seq {cfg['seq_len']}")
    w(f"- **{cfg['tokens'] / 1e6:.0f}M tokens per full arm**, identical across arms; "
      f"{cfg['steps']:,} steps at lr {cfg['lr']}")
    if env:
        w(f"- {env.get('gpu', 'GPU')} {env.get('vram_gb', '?')}GB (sm {env.get('sm', '?')}), "
          f"torch {env.get('torch', '?')} / CUDA {env.get('cuda', '?')}, fp16 + GradScaler")
    tot_flops = sum(r["total_flops"] for r in have.values())
    tot_sec = sum(r["wall_seconds"] for r in have.values())
    w(f"- {len(have)} runs, {tot_sec / 3600:.2f} GPU-hours, "
      f"{tot_flops / 1e18:.3f} EFLOPs total at "
      f"{ref['achieved_tflops']:.1f} TFLOP/s achieved\n")

    # ------------------------------------------------------------------ the bpb table
    w("## Per-domain bits-per-byte (held-out, lower is better)\n")
    w("Absolute bpb is **not** comparable across rows: a Devanagari character costs ~3 UTF-8")
    w("bytes against 1 for ASCII, so Indic rows sit lower at equal model skill. Read *across*")
    w("a row, never down a column.\n")
    cols = [n for n in FULL_ARMS if runs.get(n)] + ([SEED2] if s2 else [])
    w("| Lane | " + " | ".join(c.replace("_", " ") for c in cols) + " | σ (seed) |")
    w("|---|" + "---:|" * (len(cols) + 1))
    for ln in LANES:
        cells = [fmt(runs[c]["final_bpb"].get(ln)) if runs.get(c) else "—" for c in cols]
        w(f"| `{ln}` | " + " | ".join(cells) + f" | {fmt(sigma.get(ln))} |")
    w("")

    if sigma:
        med = sorted(sigma.values())[len(sigma) // 2]
        w(f"The seed-noise band σ is the arm-A-versus-arm-A-different-seed gap, median "
          f"**{med:.4f} bpb**. Any difference smaller than σ for its lane is treated as no "
          f"signal.\n")

    # -------------------------------------------------------------------- the verdicts
    w("## Decision rules, as declared\n")
    verdicts = []

    def cmp_lane(x, y, ln):
        """positive => x better (lower bpb) than y, in units of bpb"""
        if not x or not y:
            return None
        a, b = x["final_bpb"].get(ln), y["final_bpb"].get(ln)
        return None if a is None or b is None else b - a

    # Rule 1: A vs B
    if A and B:
        d_ind = cmp_lane(A, B, "indic_A_verified")
        d_ag = cmp_lane(A, B, "agentic")
        d_web = cmp_lane(A, B, "general_web")
        s_ind, s_ag = sigma.get("indic_A_verified", 0), sigma.get("agentic", 0)
        web_rel = (-d_web) / B["final_bpb"]["general_web"] if d_web is not None else None
        ok_ind = d_ind is not None and d_ind > s_ind
        ok_ag = d_ag is not None and d_ag > s_ag
        ok_web = web_rel is not None and web_rel <= WEB_TOLERANCE
        ok = ok_ind and ok_ag and ok_web
        w(f"**1. Mixture vs the web-heavy default — "
          f"{'CONFIRMED' if ok else 'REFUTED'}**\n")
        w(f"- verified Indic: A is {fmt(d_ind)} bpb {'better' if (d_ind or 0) > 0 else 'worse'} "
          f"than B (σ={fmt(s_ind)}) → {'passes' if ok_ind else 'FAILS'}")
        w(f"- agentic: A is {fmt(d_ag)} bpb {'better' if (d_ag or 0) > 0 else 'worse'} "
          f"than B (σ={fmt(s_ag)}) → {'passes' if ok_ag else 'FAILS'}")
        w(f"- general web cost: {web_rel * 100:+.2f}% relative "
          f"(budget {WEB_TOLERANCE * 100:.0f}%) → {'passes' if ok_web else 'FAILS'}\n")
        verdicts.append(("mixture_beats_web_heavy", ok))

    # Rule 2: the floor
    if A and C:
        d_ind = cmp_lane(A, C, "indic_A_verified")
        d_ag = cmp_lane(A, C, "agentic")
        s_ind, s_ag = sigma.get("indic_A_verified", 0), sigma.get("agentic", 0)
        ok = (d_ind or 0) > s_ind and (d_ag or 0) > s_ag
        w(f"**2. Does the protected floor earn its cost — "
          f"{'YES' if ok else 'NOT DEMONSTRATED'}**\n")
        w(f"- removing it costs {fmt(d_ind)} bpb on verified Indic (σ={fmt(s_ind)})")
        w(f"- removing it costs {fmt(d_ag)} bpb on agentic (σ={fmt(s_ag)})")
        for ln in ("general_web", "code", "stem"):
            g = cmp_lane(C, A, ln)
            w(f"- price paid on `{ln}`: {fmt(g)} bpb "
              f"{'gained by dropping the floor' if (g or 0) > 0 else 'lost'}")
        w("")
        verdicts.append(("floor_earns_its_cost", ok))

    # Rule 3: four-tier vs verified-only
    if A and D:
        d = cmp_lane(A, D, "indic_A_verified")
        s = sigma.get("indic_A_verified", 0)
        ok = (d or 0) > s
        w(f"**3. Four-tier Indic split vs verified-only — "
          f"{'CONFIRMED' if ok else 'REFUTED'}**\n")
        w(f"- on held-out verified Indic, A is {fmt(d)} bpb "
          f"{'better' if (d or 0) > 0 else 'worse'} than D (σ={fmt(s)})")
        if (d or 0) <= s:
            w("- the tiering did **not** beat spending the whole Indic budget on repeated")
            w("  verified text at this scale; reported as a refutation, not smoothed over")
        w("")
        verdicts.append(("four_tier_beats_verified_only", ok))

    # Rule 4: transition
    es = [(n, runs[n]) for n in E_ARMS if runs.get(n)]
    if es:
        w("**4. Transition stability**\n")
        w("| Probe | shift | embeddings | warmup | peak grad-norm ratio | verdict |")
        w("|---|---|---|---:|---:|---|")
        for n, r in es:
            t = r.get("transition") or {}
            frozen = "frozen" if "frozen" in n else "trainable"
            warm = f"{t.get('warmup_steps', 0)} steps"
            w(f"| `{n}` | main→anneal | {frozen} | {warm} | "
              f"{fmt(t.get('peak_ratio_x'), 2)}× | {t.get('verdict', '—')} |")
        w("")
        r1 = (runs.get("E1_hard_frozen") or {}).get("transition") or {}
        r2 = (runs.get("E2_hard_trainable") or {}).get("transition") or {}
        r3 = (runs.get("E3_warm_trainable") or {}).get("transition") or {}
        p1, p2, p3 = (x.get("peak_ratio_x") for x in (r1, r2, r3))
        if p1 and p2:
            dom = p1 > p2
            w(f"- frozen vs trainable embeddings at the *same* shift: "
              f"{fmt(p1, 2)}× vs {fmt(p2, 2)}× → "
              f"{'frozen embeddings dominate, as claimed' if dom else 'no such domination here'}")
            verdicts.append(("frozen_embeddings_dominate_spike", bool(dom)))
        if p1 and p3:
            ok = p1 > 3.0 >= p3
            w(f"- hard step {fmt(p1, 2)}× vs warmup band {fmt(p3, 2)}× against the 3× "
              f"threshold → {'reproduces' if ok else 'does not cleanly reproduce'}")
            verdicts.append(("warmup_band_controls_transition", bool(ok)))
        w("")

    # -------------------------------------------------------- lanes with nothing to say
    quiet = []
    for ln in LANES:
        vals = [runs[c]["final_bpb"].get(ln) for c in FULL_ARMS
                if runs.get(c) and runs[c]["final_bpb"].get(ln) is not None]
        if len(vals) > 1 and (max(vals) - min(vals)) <= sigma.get(ln, 0):
            quiet.append(ln)
    if quiet:
        w("## Lanes with no signal at this scale\n")
        w("Every arm lands within the seed-noise band on: "
          + ", ".join(f"`{q}`" for q in quiet) + ". Reported as no signal, not as support.\n")

    # ------------------------------------------------------------ realised mixture check
    if A:
        w("## Realised mixture and repetition (arm A)\n")
        w("| Lane | declared % | realised % | unique tokens drawn from | epochs |")
        w("|---|---:|---:|---:|---:|")
        for ln, m in sorted(A["mixture_realised"].items()):
            w(f"| `{ln}` | {m['declared_pct']:.2f} | {m['realised_pct']:.2f} | "
              f"{m['unique_cap_tokens'] / 1e6:.2f}M | {m['epochs_realised']:.2f} |")
        w("")
        starved = [ln for ln, m in A["mixture_realised"].items()
                   if m.get("cap_limited_by_pool_size")]
        if starved:
            w("Lanes whose plan-implied unique budget exceeded the pool actually available "
              "here: " + ", ".join(f"`{s}`" for s in starved) + ".\n")

    # ------------------------------------------------------------------- cost of scale
    if A:
        fpt = A["flops_per_token"]
        w("## What a real 1B/3B rung would have cost\n")
        w(f"This run: {A['params']['total'] / 1e6:.1f}M params × {cfg['tokens'] / 1e6:.0f}M "
          f"tokens ≈ {A['total_flops'] / 1e15:.2f} PFLOPs per arm, "
          f"{A['wall_seconds'] / 60:.0f} min on one T4.\n")
        w("| Rung | params | tokens (20×) | FLOPs/arm | T4-hours/arm | 7 arms |")
        w("|---|---:|---:|---:|---:|---:|")
        rate = A["total_flops"] / A["wall_seconds"]
        for name, n in (("this run", A["params"]["total"]), ("1B", 1e9), ("3B", 3e9)):
            d = 20 * n if name != "this run" else cfg["tokens"]
            f = 6 * n * d
            hrs = f / rate / 3600
            w(f"| {name} | {n / 1e6:.0f}M | {d / 1e9:.1f}B | {f / 1e18:.2f} EFLOP | "
              f"{hrs:,.0f} | {hrs * 7:,.0f} |")
        w("")
        w("At this machine's measured rate a single Chinchilla-optimal 1B arm is roughly")
        w(f"{6e9 * 20e9 / rate / 3600 / 24:,.0f} T4-days, which is why the rung below was run "
          "and labelled as such.\n")

    with open(os.path.join(PROXY, "RESULTS.md"), "w") as f:
        f.write("\n".join(out) + "\n")
    with open(os.path.join(RESULTS, "summary.json"), "w") as f:
        json.dump({"sigma": sigma, "verdicts": dict(verdicts),
                   "bpb": {n: r["final_bpb"] for n, r in have.items()}}, f, indent=1)
    print("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
